# Generated by Django 3.1 on 2020-08-29 17:13

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0003_auto_20200829_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=100, help_text='Value must be between 120-250', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=30, help_text='Value must be between 30-400', validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(30)]),
        ),
    ]
